function action(action, product) {
    // Create a new asyncronous request
    var xmlHttp = new XMLHttpRequest();

    // Create a quantity variable and set it to 0
    var quant = 0;

    // If our action is adding an item, get the quantity out of the dropdown
    if (action == "add") {
        // Reconstruct the dropdown ID.
        var addToId = product.replace('/[^a-z0-9\.]+/i', "_").replace(" ","_").toLowerCase();
        // Find the id of the dropdown
        var e = document.getElementById("quantity_" + addToId);
        // Grab the value of the selected option
        quant = e.options[e.selectedIndex].value;
    }

    // Contruct the URL using the variables
    xmlHttp.open( "GET", "api.php?action=" + action + "&item=" + product + "&quantity=" + quant, false );

    // Send the request, nothing more must be sent.
    xmlHttp.send( null );

    // grab the response, and search for the text string "done" which will be generated by the URL.
    var result = xmlHttp.responseText.search("done");

    // If we find the string, show an alert box and reload the page.
    if (result) {
        alert("Complete!");
        location.reload();
    }
    // Otherwise, show an alert saying there was an error.
    else {
        alert("There was an error try again!");
    }
}